version: '3.8'

services:
  fhir-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGE_URL: "${PACKAGE_URL}"  # Ensure correct formatting
    container_name: fhir-server
    restart: unless-stopped
    ports:
      - "${FHIR_SERVER_PORT}:8080"
    environment:
      - PACKAGE_URL=${PACKAGE_URL}  # Ensure it's available at runtime
